// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpelo-ZRKUUH2KEGGyO5U3_PeZtJNKQrY',
    appId: '1:579822847548:android:806bc4dfdbf27c5f68a539',
    messagingSenderId: '579822847548',
    projectId: 'auth-project-7cb85',
    storageBucket: 'auth-project-7cb85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgS8y5iPttH55bTEFnJ6V3TZg18ZWbDH0',
    appId: '1:579822847548:ios:805f55c7fd52272068a539',
    messagingSenderId: '579822847548',
    projectId: 'auth-project-7cb85',
    storageBucket: 'auth-project-7cb85.firebasestorage.app',
    iosClientId: '579822847548-934gkcc973n10au8svtgq5hpe9ouq4mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTest',
  );
}
